try
{
}
catch (Exception e)
{
    Console.WriteLine($"ERROR: {e.Message}");
}